export enum EPages {
  AUTHORIZATION = "AUTHORIZATION",
  ACCOUNT = "ACCOUNT",
  ORDERS = "ORDERS",
  TABLES = "TABLES",
  MENU = "MENU",
  ADDING_MENU = "ADDING_MENU",
  ELEMENTS = "ELEMENTS",
  CATEGORIES = "CATEGORIES",
  KITCHEN = "KITCHEN",
}
