export enum EPages {
  AUTHORIZATION = "AUTHORIZATION",
  COMPANY = "COMPANY",
  ORDERS = "ORDERS",
  TABLES = "TABLES",
  ELEMENTS = "ELEMENTS",
  CATEGORIES = "CATEGORIES",
  KITCHEN = "KITCHEN",
  REPORTS = "REPORTS",
  POSITIONS = "POSITIONS",
  HOME = "HOME",
  USERS = "USERS",
  END_OF_THE_DAY = "END_OF_THE_DAY",
}
