export enum EPages {
  AUTHORIZATION = "AUTHORIZATION",
  ACCOUNT = "ACCOUNT",
  ORDERS = "ORDERS",
  TABLES = "TABLES",
  ELEMENTS = "ELEMENTS",
  CATEGORIES = "CATEGORIES",
  KITCHEN = "KITCHEN",
  REPORTS = "REPORTS",
  POSITIONS = "POSITIONS",
  HOME = "HOME",
}
